[tool.black]
line-lenght = 120
target-version = ['py310', 'py311']
skip_magic_trailing_comma = true


[tool.flake8]
exclude = ['venv', '.venv']
ignore = ['W503', 'E203']
max-coplexity = 10
max-line-lenght = 120