# Generated by Django 4.2.1 on 2023-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, verbose_name="Full name")),
                ("email", models.EmailField(max_length=254, verbose_name="user email")),
                (
                    "instagram",
                    models.CharField(max_length=50, verbose_name="user Instagram"),
                ),
                ("message", models.TextField(max_length=500, verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New feedback"),
                            ("P", "feedback in process"),
                            ("F", "feedback was process"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="feedback status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created feedback"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last updated"),
                ),
            ],
            options={"verbose_name": "Feed back", "db_table": "feedback"},
        )
    ]
